# Generated by Django 5.2.4 on 2025-09-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Bus', 'Bus')], max_length=10)),
                ('entry_time', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
