# Generated by Django 5.2.6 on 2025-09-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(help_text='The detected license plate number.', max_length=15, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The date and time when the plate was first detected.')),
            ],
        ),
    ]
